
import { APExam } from './types';

export const AP_EXAMS: APExam[] = [
  { id: 'art-history', title: 'AP Art History', description: 'Explore art from ancient cultures to the present day.', subjects: ['History', 'Art'], mcqCount: 80, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'biology', title: 'AP Biology', description: 'Dive into the core principles of biology.', subjects: ['Science'], mcqCount: 60, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'calculus-ab', title: 'AP Calculus AB', description: 'Master differential and integral calculus.', subjects: ['Math'], mcqCount: 45, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'calculus-bc', title: 'AP Calculus BC', description: 'Extend your calculus knowledge with advanced topics.', subjects: ['Math'], mcqCount: 45, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'chemistry', title: 'AP Chemistry', description: 'Investigate the world of atoms, molecules, and reactions.', subjects: ['Science'], mcqCount: 60, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'chinese-language', title: 'AP Chinese Language and Culture', description: 'Develop your proficiency in Mandarin Chinese.', subjects: ['Language'], mcqCount: 65, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'comparative-government', title: 'AP Comparative Government and Politics', description: 'Compare political systems across the world.', subjects: ['Social Studies'], mcqCount: 55, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'computer-science-a', title: 'AP Computer Science A', description: 'Learn object-oriented programming with Java.', subjects: ['Computer Science'], mcqCount: 40, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'computer-science-principles', title: 'AP Computer Science Principles', description: 'Understand the fundamentals of computing.', subjects: ['Computer Science'], mcqCount: 70, questionTypes: ['MCQ'] },
  { id: 'english-language', title: 'AP English Language and Composition', description: 'Analyze rhetoric and compose effective arguments.', subjects: ['English'], mcqCount: 45, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'english-literature', title: 'AP English Literature and Composition', description: 'Explore and analyze great literary works.', subjects: ['English'], mcqCount: 55, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'environmental-science', title: 'AP Environmental Science', description: 'Examine the interrelationships of the natural world.', subjects: ['Science'], mcqCount: 80, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'european-history', title: 'AP European History', description: 'Journey through European history from 1450 to the present.', subjects: ['History'], mcqCount: 55, questionTypes: ['MCQ', 'SAQ', 'DBQ', 'LEQ'] },
  { id: 'french-language', title: 'AP French Language and Culture', description: 'Enhance your skills in French language and culture.', subjects: ['Language'], mcqCount: 65, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'german-language', title: 'AP German Language and Culture', description: 'Build your proficiency in German.', subjects: ['Language'], mcqCount: 65, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'human-geography', title: 'AP Human Geography', description: 'Study the patterns and processes that shape human society.', subjects: ['Social Studies'], mcqCount: 60, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'italian-language', title: 'AP Italian Language and Culture', description: 'Master the Italian language.', subjects: ['Language'], mcqCount: 65, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'japanese-language', title: 'AP Japanese Language and Culture', description: 'Develop your proficiency in Japanese.', subjects: ['Language'], mcqCount: 65, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'latin', title: 'AP Latin', description: 'Read and analyze classical Latin literature.', subjects: ['Language'], mcqCount: 50, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'macroeconomics', title: 'AP Macroeconomics', description: 'Understand the principles of economics on a national scale.', subjects: ['Social Studies'], mcqCount: 60, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'microeconomics', title: 'AP Microeconomics', description: 'Analyze the behavior of individuals and firms in markets.', subjects: ['Social Studies'], mcqCount: 60, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'music-theory', title: 'AP Music Theory', description: 'Learn the fundamentals of music composition and theory.', subjects: ['Art'], mcqCount: 75, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'physics-1', title: 'AP Physics 1: Algebra-Based', description: 'Explore introductory Newtonian mechanics.', subjects: ['Science'], mcqCount: 50, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'physics-2', title: 'AP Physics 2: Algebra-Based', description: 'Explore fluid mechanics, thermodynamics, and more.', subjects: ['Science'], mcqCount: 50, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'physics-c-em', title: 'AP Physics C: Electricity and Magnetism', description: 'Delve into calculus-based electricity and magnetism.', subjects: ['Science'], mcqCount: 35, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'physics-c-mech', title: 'AP Physics C: Mechanics', description: 'Study calculus-based classical mechanics.', subjects: ['Science'], mcqCount: 35, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'psychology', title: 'AP Psychology', description: 'Explore the scientific study of behavior and mental processes.', subjects: ['Social Studies'], mcqCount: 100, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'research', title: 'AP Research', description: 'Conduct a year-long, college-level research project.', subjects: ['General'], mcqCount: 0, questionTypes: [] },
  { id: 'seminar', title: 'AP Seminar', description: 'Develop critical thinking and research skills.', subjects: ['General'], mcqCount: 0, questionTypes: [] },
  { id: 'spanish-language', title: 'AP Spanish Language and Culture', description: 'Build your proficiency in Spanish.', subjects: ['Language'], mcqCount: 65, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'spanish-literature', title: 'AP Spanish Literature and Culture', description: 'Read and analyze Spanish literary works.', subjects: ['Language'], mcqCount: 65, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'statistics', title: 'AP Statistics', description: 'Learn to collect, analyze, and draw conclusions from data.', subjects: ['Math'], mcqCount: 40, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'studio-art-2d', title: 'AP 2-D Art and Design', description: 'Create a portfolio of 2-D artwork.', subjects: ['Art'], mcqCount: 0, questionTypes: [] },
  { id: 'studio-art-3d', title: 'AP 3-D Art and Design', description: 'Create a portfolio of 3-D artwork.', subjects: ['Art'], mcqCount: 0, questionTypes: [] },
  { id: 'us-government', title: 'AP United States Government and Politics', description: 'Understand the American political system.', subjects: ['Social Studies'], mcqCount: 55, questionTypes: ['MCQ', 'FRQ'] },
  { id: 'us-history', title: 'AP United States History', description: 'Survey American history from the colonial era to the present.', subjects: ['History'], mcqCount: 55, questionTypes: ['MCQ', 'SAQ', 'DBQ', 'LEQ'] },
  { id: 'world-history', title: 'AP World History: Modern', description: 'Explore world history from 1200 CE to the present.', subjects: ['History'], mcqCount: 55, questionTypes: ['MCQ', 'SAQ', 'DBQ', 'LEQ'] },
];
